parameters:
# parameters

services:
    security.systemuser.registration.type:
        class: HatueySoft\SecurityBundle\Form\Type\UsuarioType
        arguments: [@configuration.reader]
        tags:
            - { name: form.type, alias: hatueysoft_security_usuario_type }

    security.role.type:
        class: HatueySoft\SecurityBundle\Form\Type\RoleType
        arguments:
            - @configuration.reader
        tags:
            - { name: form.type, alias: hatueysoft_security_role_type }

    # VALIDATORS
    security.unique_systemuser_username.validator:
        class: HatueySoft\SecurityBundle\Validator\Constraints\UniqueSystemUserUsernameValidator
        arguments:
            - @fos_user.user_manager
        tags:
            - {name: validator.constraint_validator, alias: unique_systemuser_username_validator}

    security.unique_systemuser_email.validator:
        class: HatueySoft\SecurityBundle\Validator\Constraints\UniqueSystemUserEmailValidator
        arguments:
            - @fos_user.user_manager
        tags:
            - {name: validator.constraint_validator, alias: unique_systemuser_email_validator}

    #SECURITY MANAGERS
    security.manager:
         class: HatueySoft\SecurityBundle\Manager\SecurityManager
         arguments: [ %security_config% ]

    configuration.reader:
         class: HatueySoft\SecurityBundle\Utils\ConfigurationReader
         arguments: [ @service_container, %security_config% ]

    hatuey_soft.security.acl_manager:
        class: HatueySoft\SecurityBundle\Manager\AclManager
        arguments: [@service_container]

    hatuey_soft.security.acl_rules_manager:
        class: HatueySoft\SecurityBundle\Manager\AclRulesManager
        arguments: [@service_container]

    hatuey_soft.voter_attributes_checker:
        class: HatueySoft\SecurityBundle\Utils\VoterAttributesChecker

    hatuey_soft.voter_class_checker:
        class: HatueySoft\SecurityBundle\Utils\VoterClassChecker
        arguments:
            - @hatuey_soft.security.acl_rules_manager

    #SUBSCRIBERS
    hatuey_soft.doctrine_subscriber.acl_aware:
        class: HatueySoft\SecurityBundle\Doctrine\Subscribers\AclSubscriber
        arguments:
            - @hatuey_soft.security.acl_manager
            - @hatuey_soft.security.acl_rules_manager
            - %hatuey_soft_security.config%
        tags:
            - { name: doctrine.event_subscriber }

    hatuey_soft.security.user_callable:
        class: HatueySoft\SecurityBundle\Doctrine\UserCallable
        arguments:
                - @service_container

    hatuey_soft.acl_provider_callable:
        class: HatueySoft\SecurityBundle\Doctrine\AclProviderCallable
        arguments:
            - @service_container

    hatuey_soft.doctrine_subscriber.datetime_aware:
        class: HatueySoft\SecurityBundle\Doctrine\Subscribers\DateTimeSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    hatuey_soft.doctrine_subscriber.user_aware:
        class: HatueySoft\SecurityBundle\Doctrine\Subscribers\UserSubscriber
        arguments:
            - @hatuey_soft.security.user_callable
        tags:
            - { name: doctrine.event_subscriber }

    #Voters
    security.access.default_entity_actions_voter:
        class: HatueySoft\SecurityBundle\Voter\EntitiesActionsVoter
        arguments:
            - @hatuey_soft.security.acl_rules_manager
            - @hatuey_soft.voter_attributes_checker
            - @hatuey_soft.voter_class_checker
        public: false
        tags:
            - {name: security.voter}
