compra:
    path:  /
    defaults: { _controller: "BusetaTallerBundle:Compra:index" }

compra_show:
    path:  /{id}/show
    defaults: { _controller: "BusetaTallerBundle:Compra:show" }

compra_new:
    path:  /new
    defaults: { _controller: "BusetaTallerBundle:Compra:new" }

compra_create:
    path:  /create
    defaults: { _controller: "BusetaTallerBundle:Compra:create" }
    requirements: { methods: post }

compra_edit:
    path:  /{id}/edit
    defaults: { _controller: "BusetaTallerBundle:Compra:edit" }

compra_update:
    path:  /{id}/update
    defaults: { _controller: "BusetaTallerBundle:Compra:update" }
    requirements: { methods: post|put }

compra_delete:
    path:  /{id}/delete
    defaults: { _controller: "BusetaTallerBundle:Compra:delete" }
    requirements: { methods: post|delete }

guardarPedido:
  path: /guardarPedido
  defaults: { _controller: "BusetaTallerBundle:Compra:guardarPedido" }
  requirements: { methods: "GET" }
  options:
      expose: true
