condicionespago:
    path:  /
    defaults: { _controller: "BusetaTallerBundle:CondicionesPago:index" }

condicionespago_show:
    path:  /{id}/show
    defaults: { _controller: "BusetaTallerBundle:CondicionesPago:show" }

condicionespago_new:
    path:  /new
    defaults: { _controller: "BusetaTallerBundle:CondicionesPago:new" }

condicionespago_create:
    path:  /create
    defaults: { _controller: "BusetaTallerBundle:CondicionesPago:create" }
    requirements: { methods: post }

condicionespago_edit:
    path:  /{id}/edit
    defaults: { _controller: "BusetaTallerBundle:CondicionesPago:edit" }

condicionespago_update:
    path:  /{id}/update
    defaults: { _controller: "BusetaTallerBundle:CondicionesPago:update" }
    requirements: { methods: post|put }

condicionespago_delete:
    path:  /{id}/delete
    defaults: { _controller: "BusetaTallerBundle:CondicionesPago:delete" }
    requirements: { methods: post|delete }
