impuesto:
    path:  /
    defaults: { _controller: "BusetaTallerBundle:Impuesto:index" }

impuesto_show:
    path:  /{id}/show
    defaults: { _controller: "BusetaTallerBundle:Impuesto:show" }

impuesto_new:
    path:  /new
    defaults: { _controller: "BusetaTallerBundle:Impuesto:new" }

impuesto_create:
    path:  /create
    defaults: { _controller: "BusetaTallerBundle:Impuesto:create" }
    requirements: { methods: post }

impuesto_edit:
    path:  /{id}/edit
    defaults: { _controller: "BusetaTallerBundle:Impuesto:edit" }

impuesto_update:
    path:  /{id}/update
    defaults: { _controller: "BusetaTallerBundle:Impuesto:update" }
    requirements: { methods: post|put }

impuesto_delete:
    path:  /{id}/delete
    defaults: { _controller: "BusetaTallerBundle:Impuesto:delete" }
    requirements: { methods: post|delete }

impuesto_ajax_productos_all:
  path: /select_impuesto_productos_all
  defaults: { _controller: "BusetaTallerBundle:Impuesto:select_impuesto_productos_all" }
  requirements: { methods: "GET" }
  options:
      expose: true
