linea:
    pattern:  /
    defaults: { _controller: "BusetaTallerBundle:Linea:index" }

linea_show:
    pattern:  /{id}/show
    defaults: { _controller: "BusetaTallerBundle:Linea:show" }

linea_new:
    pattern:  /new
    defaults: { _controller: "BusetaTallerBundle:Linea:new" }

linea_create:
    pattern:  /create
    defaults: { _controller: "BusetaTallerBundle:Linea:create" }
    requirements: { _method: post }

linea_compra_create:
    pattern:  /create
    defaults: { _controller: "BusetaTallerBundle:Linea:create_compra" }
    requirements: { _method: post }

linea_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BusetaTallerBundle:Linea:edit" }

linea_update:
    pattern:  /{id}/update
    defaults: { _controller: "BusetaTallerBundle:Linea:update" }
    requirements: { _method: post|put }

linea_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BusetaTallerBundle:Linea:delete" }
    requirements: { _method: post|delete }
