observacion:
    path:  /
    defaults: { _controller: "BusetaTallerBundle:Observacion:index" }

observacion_show:
    path:  /{id}/show
    defaults: { _controller: "BusetaTallerBundle:Observacion:show" }

observacion_new:
    path:  /new
    defaults: { _controller: "BusetaTallerBundle:Observacion:new" }

observacion_create:
    path:  /create
    defaults: { _controller: "BusetaTallerBundle:Observacion:create" }
    requirements: { methods: post }

observacion_reporte_create:
    path:  /create
    defaults: { _controller: "BusetaTallerBundle:Observacion:create_reporte" }
    requirements: { methods: post }

observacion_edit:
    path:  /{id}/edit
    defaults: { _controller: "BusetaTallerBundle:Observacion:edit" }

observacion_update:
    path:  /{id}/update
    defaults: { _controller: "BusetaTallerBundle:Observacion:update" }
    requirements: { methods: post|put }

observacion_delete:
    path:  /{id}/delete
    defaults: { _controller: "BusetaTallerBundle:Observacion:delete" }
    requirements: { methods: post|delete }

observacion_new_modal:
    path: /modal/new
    defaults: { _controller: "BusetaTallerBundle:Observacion:newModalObservacion" }
    requirements: { methods: get }
    options:
      expose: true

observacion_diagnostico_new_modal:
    path: /modal_observacion/new
    defaults: { _controller: "BusetaTallerBundle:Observacion:newModalObservacionDiagnostico" }
    requirements: { methods: get }
    options:
      expose: true
