observaciondiagnostico:
    pattern:  /
    defaults: { _controller: "BusetaTallerBundle:ObservacionDiagnostico:index" }

observaciondiagnostico_show:
    pattern:  /{id}/show
    defaults: { _controller: "BusetaTallerBundle:ObservacionDiagnostico:show" }

observaciondiagnostico_new:
    pattern:  /new
    defaults: { _controller: "BusetaTallerBundle:ObservacionDiagnostico:new" }

observaciondiagnostico_create:
    pattern:  /create
    defaults: { _controller: "BusetaTallerBundle:ObservacionDiagnostico:create" }
    requirements: { _method: post }

observaciondiagnostico_reporte_create:
    pattern:  /create
    defaults: { _controller: "BusetaTallerBundle:ObservacionDiagnostico:create_reporte" }
    requirements: { _method: post }

observaciondiagnostico_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BusetaTallerBundle:ObservacionDiagnostico:edit" }

observaciondiagnostico_update:
    pattern:  /{id}/update
    defaults: { _controller: "BusetaTallerBundle:ObservacionDiagnostico:update" }
    requirements: { _method: post|put }

observaciondiagnostico_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BusetaTallerBundle:ObservacionDiagnostico:delete" }
    requirements: { _method: post|delete }

observaciondiagnostico_new_modal:
    pattern: /modal/new
    defaults: { _controller: "BusetaTallerBundle:ObservacionDiagnostico:newModalObservacionDiagnostico" }
    requirements: { _method: get }
    options:
      expose: true