observaciondiagnostico:
    path:  /
    defaults: { _controller: "BusetaTallerBundle:ObservacionDiagnostico:index" }

observaciondiagnostico_show:
    path:  /{id}/show
    defaults: { _controller: "BusetaTallerBundle:ObservacionDiagnostico:show" }

observaciondiagnostico_new:
    path:  /new
    defaults: { _controller: "BusetaTallerBundle:ObservacionDiagnostico:new" }

observaciondiagnostico_create:
    path:  /create
    defaults: { _controller: "BusetaTallerBundle:ObservacionDiagnostico:create" }
    requirements: { methods: post }

observaciondiagnostico_reporte_create:
    path:  /create
    defaults: { _controller: "BusetaTallerBundle:ObservacionDiagnostico:create_reporte" }
    requirements: { methods: post }

observaciondiagnostico_edit:
    path:  /{id}/edit
    defaults: { _controller: "BusetaTallerBundle:ObservacionDiagnostico:edit" }

observaciondiagnostico_update:
    path:  /{id}/update
    defaults: { _controller: "BusetaTallerBundle:ObservacionDiagnostico:update" }
    requirements: { methods: post|put }

observaciondiagnostico_delete:
    path:  /{id}/delete
    defaults: { _controller: "BusetaTallerBundle:ObservacionDiagnostico:delete" }
    requirements: { methods: post|delete }

observaciondiagnostico_new_modal:
    path: /modal/new
    defaults: { _controller: "BusetaTallerBundle:ObservacionDiagnostico:newModalObservacionDiagnostico" }
    requirements: { methods: get }
    options:
      expose: true
