ordentrabajo:
    path:  /
    defaults: { _controller: "BusetaTallerBundle:OrdenTrabajo:index" }

ordentrabajo_show:
    path:  /{id}/show
    defaults: { _controller: "BusetaTallerBundle:OrdenTrabajo:show" }

ordentrabajo_new:
    path:  /new
    defaults: { _controller: "BusetaTallerBundle:OrdenTrabajo:new" }

ordentrabajo_create:
    path:  /create
    defaults: { _controller: "BusetaTallerBundle:OrdenTrabajo:create" }
    requirements: { methods: post }

ordentrabajo_edit:
    path:  /{id}/edit
    defaults: { _controller: "BusetaTallerBundle:OrdenTrabajo:edit" }

ordentrabajo_update:
    path:  /{id}/update
    defaults: { _controller: "BusetaTallerBundle:OrdenTrabajo:update" }
    requirements: { methods: post|put }

ordentrabajo_delete:
    path:  /{id}/delete
    defaults: { _controller: "BusetaTallerBundle:OrdenTrabajo:delete" }
    requirements: { methods: post|delete }

ajax_select_autobus_mpreventivo:
    path: /select_autobus_mpreventivo
    defaults: { _controller: "BusetaTallerBundle:OrdenTrabajo:selectAutobusMantenimientoPreventivo" }
    requirements: { methods: "GET" }
    options:
        expose: true

ajax_select_autobus_kilometraje:
    path: /select_autobus_kilometraje
    defaults: { _controller: "BusetaTallerBundle:OrdenTrabajo:selectAutobusKilometraje" }
    requirements: { methods: "GET" }
    options:
        expose: true

diagnostico_ajax_diag_diagpor:
    path: /select_diag_diagpor
    defaults: { _controller: "BusetaTallerBundle:OrdenTrabajo:selectdiagdiagpor" }
    requirements: { methods: "GET" }
    options:
        expose: true

ordentrabajo_ajax_salidabodega:
    path: /select_salidadbodega_ordentrabajo
    defaults: { _controller: "BusetaTallerBundle:OrdenTrabajo:select_salidabodega_ordentrabajo" }
    requirements: { methods: "GET" }
    options:
      expose: true

ordentrabajo_ajax_diagnostico_autobus:
    path: /select_filter_diagnostico_autobus
    defaults: { _controller: "BusetaTallerBundle:OrdenTrabajo:select_diagnostico_autobus" }
    requirements: { methods: "GET" }
    options:
      expose: true

ordentrabajoprocesarconfirm:
    path:  /{id}/procesarOrdenConfirm
    defaults: { _controller: "BusetaTallerBundle:OrdenTrabajo:procesarOrdenConfirm" }

procesarOrden:
    path:  /{id}/procesarOrden
    defaults: { _controller: "BusetaTallerBundle:OrdenTrabajo:procesarOrden" }

completarOrden:
    path:  /{id}/completarOrden
    defaults: { _controller: "BusetaTallerBundle:OrdenTrabajo:completarOrden" }

cancelarOrden:
    path:  /{id}/cancelarOrden
    defaults: { _controller: "BusetaTallerBundle:OrdenTrabajo:cancelarOrden" }






