reporte:
    path: /
    defaults: { _controller: "BusetaTallerBundle:Reporte:principal" }

reporte_index:
    path:  /index
    defaults: { _controller: "BusetaTallerBundle:Reporte:index" }

reporte_show:
    path:  /{id}/show
    defaults: { _controller: "BusetaTallerBundle:Reporte:show" }

reporte_new:
    path:  /new
    defaults: { _controller: "BusetaTallerBundle:Reporte:new" }

reporte_create:
    path:  /create
    defaults: { _controller: "BusetaTallerBundle:Reporte:create" }
    requirements: { methods: post }

reporte_edit:
    path:  /{id}/edit
    defaults: { _controller: "BusetaTallerBundle:Reporte:edit" }

reporte_update:
    path:  /{id}/update
    defaults: { _controller: "BusetaTallerBundle:Reporte:update" }
    requirements: { methods: post|put }

reporte_delete:
    path:  /{id}/delete
    defaults: { _controller: "BusetaTallerBundle:Reporte:delete" }
    requirements: { methods: post|delete }

procesarReporte:
    path:  /{id}/procesarReporte
    defaults: { _controller: "BusetaTallerBundle:Reporte:procesarReporte" }

reporte_generar_diagnostico:
    path:  /{id}/generar_diagnostico
    defaults: { _controller: "BusetaTallerBundle:Reporte:generarDiagnostico" }
