tareaadicional:
    path:  /
    defaults: { _controller: "BusetaTallerBundle:TareaAdicional:index" }

tareaadicional_show:
    path:  /{id}/show
    defaults: { _controller: "BusetaTallerBundle:TareaAdicional:show" }

tareaadicional_new:
    path:  /new
    defaults: { _controller: "BusetaTallerBundle:TareaAdicional:new" }

tareaadicional_create:
    path:  /create
    defaults: { _controller: "BusetaTallerBundle:TareaAdicional:create" }
    requirements: { methods: post }

tarea_adicional_orden_trabajo_create:
    path:  /create
    defaults: { _controller: "BusetaTallerBundle:TareaAdicional:create_orden_trabajo" }
    requirements: { methods: post }

tareaadicional_edit:
    path:  /{id}/edit
    defaults: { _controller: "BusetaTallerBundle:TareaAdicional:edit" }

tareaadicional_update:
    path:  /{id}/update
    defaults: { _controller: "BusetaTallerBundle:TareaAdicional:update" }
    requirements: { methods: post|put }

tareaadicional_delete:
    path:  /{id}/delete
    defaults: { _controller: "BusetaTallerBundle:TareaAdicional:delete" }
    requirements: { methods: post|delete }

tareaadicional_new_modal:
    path: /modal/new
    defaults: { _controller: "BusetaTallerBundle:TareaAdicional:newModal" }
    requirements: { methods: get }
    options:
      expose: true
