tareamantenimiento:
    path:  /
    defaults: { _controller: "BusetaTallerBundle:TareaMantenimiento:index" }

tareamantenimiento_show:
    path:  /{id}/show
    defaults: { _controller: "BusetaTallerBundle:TareaMantenimiento:show" }

tareamantenimiento_new:
    path:  /new
    defaults: { _controller: "BusetaTallerBundle:TareaMantenimiento:new" }

tareamantenimiento_create:
    path:  /create
    defaults: { _controller: "BusetaTallerBundle:TareaMantenimiento:create" }
    requirements: { methods: post }

tareamantenimiento_edit:
    path:  /{id}/edit
    defaults: { _controller: "BusetaTallerBundle:TareaMantenimiento:edit" }

tareamantenimiento_update:
    path:  /{id}/update
    defaults: { _controller: "BusetaTallerBundle:TareaMantenimiento:update" }
    requirements: { methods: post|put }

tareamantenimiento_delete:
    path:  /{id}/delete
    defaults: { _controller: "BusetaTallerBundle:TareaMantenimiento:delete" }
    requirements: { methods: post|delete }

tareamantenimiento_ajax_grupos_subgrupos:
  path: /select_grupo_subgrupo
  defaults: { _controller: "BusetaTallerBundle:TareaMantenimiento:select_grupo_subgrupo" }
  requirements: { methods: "GET" }
  options:
      expose: true

tareamantenimiento_ajax_subgrupos_productos:
  path: /select_subgrupo_producto
  defaults: { _controller: "BusetaTallerBundle:TareaMantenimiento:select_subgrupo_producto" }
  requirements: { methods: "GET" }
  options:
      expose: true
