grupo:
    pattern:  /
    defaults: { _controller: "NomencladorBundle:Grupo:index" }

grupo_show:
    pattern:  /{id}/show
    defaults: { _controller: "NomencladorBundle:Grupo:show" }

grupo_new:
    pattern:  /new
    defaults: { _controller: "NomencladorBundle:Grupo:new" }

grupo_create:
    pattern:  /create
    defaults: { _controller: "NomencladorBundle:Grupo:create" }
    requirements: { _method: post }

grupo_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "NomencladorBundle:Grupo:edit" }

grupo_update:
    pattern:  /{id}/update
    defaults: { _controller: "NomencladorBundle:Grupo:update" }
    requirements: { _method: post|put }

grupo_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "NomencladorBundle:Grupo:delete" }
    requirements: { _method: post|delete }
