marca:
    pattern:  /
    defaults: { _controller: "NomencladorBundle:Marca:index" }

marca_show:
    pattern:  /{id}/show
    defaults: { _controller: "NomencladorBundle:Marca:show" }

marca_new:
    pattern:  /new
    defaults: { _controller: "NomencladorBundle:Marca:new" }

marca_create:
    pattern:  /create
    defaults: { _controller: "NomencladorBundle:Marca:create" }
    requirements: { _method: post }

marca_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "NomencladorBundle:Marca:edit" }

marca_update:
    pattern:  /{id}/update
    defaults: { _controller: "NomencladorBundle:Marca:update" }
    requirements: { _method: post|put }

marca_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "NomencladorBundle:Marca:delete" }
    requirements: { _method: post|delete }
