parameters:
#    buseta_template.example.class: Buseta\TemplateBundle\Example

services:
#    buseta_template.example:
#        class: %buseta_template.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
