parameters:
    consecutivoCompra: 89
#    buseta_taller.example.class: Buseta\TallerBundle\Example

services:
    taller.compra.type:
        class: Buseta\TallerBundle\Form\Type\CompraType
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: form.type, alias: 'taller_compra'}
