services:
  hatueysoft.fecha_sistema.manager:
    class: HatueySoft\DateTimeBundle\Managers\FechaSistemaManager
    arguments:
      - @doctrine.orm.entity_manager
      - @hatueysoft.hora_sistema.manager
      - @security.token_storage

  hatueysoft.hora_sistema.manager:
    class: HatueySoft\DateTimeBundle\Managers\HoraSistemaManager
    arguments:
      - @doctrine.orm.entity_manager

  # TWIG EXTENSION
  hatueysoft.fecha_sistema.twig_extension:
    class: HatueySoft\DateTimeBundle\Twig\FechaSistemaExtension
    arguments:
        - @hatueysoft.fecha_sistema.manager
    tags:
        - { name: twig.extension }
