core_homepage:
    path:  /
    defaults: { _controller: CoreBundle:Default:index }

configuracion_principal:
    path:  /modulo/configuracion
    defaults: { _controller: "CoreBundle:Default:principal" }
