parameters:
#    core.example.class: Buseta\CoreBundle\Example

services:
#    core.example:
#        class: %core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

#VALIDATORS
    core.codigoypin.validador:
        class: Buseta\CoreBundle\Validator\Constraints\CodigoYPinValidoValidator
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - {name: validator.constraint_validator, alias: codigoYpin_validador}

    #TWIG EXTENSIONS
    core.twig.moneda_simbolo_extension:
        class: Buseta\CoreBundle\Twig\MonedaSimboloExtension
        arguments:
            - @doctrine.orm.default_entity_manager
            - @session
        tags:
            - { name: twig.extension }
    core.twig.fecha_formato_extension:
        class: Buseta\CoreBundle\Twig\FechaFormatoExtension
        arguments:
            - @doctrine.orm.default_entity_manager
            - @session
        tags:
            - { name: twig.extension }
