parameters:
#    core.example.class: Buseta\CoreBundle\Example

services:
#    core.example:
#        class: %core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

#VALIDATORS
    core.codigoypin.validador:
        class: Buseta\CoreBundle\Validator\Constraints\CodigoYPinValidoValidator
        arguments:
            - @security.context
            - @doctrine.orm.entity_manager
        tags:
            - {name: validator.constraint_validator, alias: codigoYpin_validador}