parameters:
#    core.example.class: Buseta\CoreBundle\Example

services:
#    core.example:
#        class: %core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

#VALIDATORS
    core.codigoypin.validador:
        class: Buseta\CoreBundle\Validator\Constraints\CodigoYPinValidoValidator
        arguments:
            - @security.context
            - @doctrine.orm.entity_manager
        tags:
            - {name: validator.constraint_validator, alias: codigoYpin_validador}
    core.fecha_sistema:
        class: Buseta\CoreBundle\Managers\FechaSistemaManager
        arguments:
            - @doctrine.orm.entity_manager
            - @core.cambiohora_sistema

    core.cambiohora_sistema:
        class: Buseta\CoreBundle\Managers\CambioHoraSistemaManager
        arguments:
            - @doctrine.orm.entity_manager

#SUBSCRIBER
    core.doctrine_subscriber.datetime_aware:
        class: Buseta\CoreBundle\Doctrine\DateTimeSubscriber
        tags:
            - { name: doctrine.event_subscriber }
