root:
  id: root
  name: null
  label: null
  route: null
  roles:
    - ROLE_USER
  type: folder
  attributes: {  }
  childrens:
    menu:
      id: menu
      name: null
      label: 'Menú sistema'
      route: null
      roles:
        - ROLE_USER
      type: folder
      attributes: {  }
      childrens:
        menu_A:
          id: menu_A
          name: menu_vehiculos
          label: Vehículos
          route: autobus_principal
          roles:
            - ROLE_USER
          type: folder
          attributes:
            icon: 'fa fa-bus'
            color: bg-color-blue
          childrens:
            menu_A_A:
              id: menu_A_A
              name: null
              label: 'Página principal'
              route: core_homepage
              roles:
                - ROLE_USER
              type: item
              attributes:
                icon: 'fa fa-dashboard'
              childrens: {  }
            menu_A_B:
              id: menu_A_B
              name: null
              label: 'Gestión de vehículos'
              route: null
              roles:
                - ROLE_USER
              type: folder
              attributes:
                icon: 'fa fa-wrench'
              childrens:
                menu_A_B_A:
                  id: menu_A_B_A
                  name: null
                  label: Autobuses
                  route: null
                  roles: [ROLE_USER]
                  type: item
                  attributes: { icon: null }
                  childrens: {  }
                menu_A_B_B:
                  id: menu_A_B_B
                  name: null
                  label: Choferes
                  route: null
                  roles: [ROLE_USER]
                  type: item
                  attributes: { icon: null }
                  childrens: {  }
                menu_A_B_C:
                  id: menu_A_B_C
                  name: null
                  label: Vehículos
                  route: null
                  roles: [ROLE_USER]
                  type: item
                  attributes: { icon: null }
                  childrens: {  }
            menu_A_C:
              id: menu_A_C
              name: null
              label: Configuración
              route: null
              roles:
                - ROLE_USER
              type: folder
              attributes:
                icon: 'fa fa-gear'
              childrens:
                menu_A_C_A:
                  id: menu_A_C_A
                  name: null
                  label: 'Cambio hora del sistema'
                  route: null
                  roles: [ROLE_USER]
                  type: item
                  attributes: { icon: null }
                  childrens: {  }
                menu_A_C_B:
                  id: menu_A_C_B
                  name: null
                  label: 'Cambio fecha del sistema'
                  route: null
                  roles: [ROLE_USER]
                  type: item
                  attributes: { icon: null }
                  childrens: {  }
        menu_B:
          id: menu_B
          name: menu_bodega
          label: Bodega
          route: bodega_principal
          roles:
            - ROLE_USER
          type: folder
          attributes:
            icon: 'fa fa-cubes'
            color: bg-color-orange
          childrens:
            menu_B_A:
              id: menu_B_A
              name: null
              label: 'Página principal'
              route: core_homepage
              roles:
                - ROLE_USER
              type: item
              attributes:
                icon: 'fa fa-dashboard'
              childrens: {  }
        menu_C:
          id: menu_C
          name: menu_taller
          label: Taller
          route: taller_principal
          roles:
            - ROLE_USER
          type: folder
          attributes:
            icon: 'fa fa-cogs'
            color: bg-color-green
          childrens: {  }
        menu_D:
          id: menu_D
          name: menu_combustible
          label: Combustible
          route: configuracion_combustible
          roles:
            - ROLE_USER
          type: folder
          attributes:
            icon: 'fa fa-dashboard'
            color: bg-color-blueDark
          childrens: {  }
        menu_E:
          id: menu_E
          name: menu_nomenclador
          label: 'Módulo Nomenclador'
          route: admin
          roles:
            - ROLE_USER
          type: item
          attributes:
            icon: 'fa fa-cog'
            color: bg-color-brown
          childrens: {  }
        menu_F:
          id: menu_F
          name: menu_seguridad
          label: 'Módulo Seguridad'
          route: security_usuario
          roles:
            - ROLE_USER
          type: folder
          attributes:
            icon: 'fa fa-shield'
            color: bg-color-red
          childrens: {  }
