root:
  id: root
  name: null
  label: null
  route: null
  roles: null
  type: folder
  attributes: {  }
  childrens:
    menu:
      id: menu
      name: null
      label: 'Menú sistema'
      route: null
      roles: null
      type: folder
      attributes: {  }
      childrens:
        menu_A:
          id: menu_A
          name: menu_vehiculos
          label: Vehículos
          route: autobus_principal
          roles: {  }
          type: folder
          attributes:
            icon: null
          childrens:
            menu_A_A:
              id: menu_A_A
              name: null
              label: 'Página principal'
              route: autobus_principal
              roles: {  }
              type: item
              attributes:
                icon: null
              childrens: {  }
            menu_A_B:
              id: menu_A_B
              name: null
              label: 'Gestión de vehículos'
              route: null
              roles: {  }
              type: folder
              attributes:
                icon: null
              childrens:
                menu_A_B_A:
                  id: menu_A_B_A
                  name: null
                  label: Autobuses
                  route: null
                  roles: {  }
                  type: item
                  attributes: { icon: null }
                  childrens: {  }
                menu_A_B_B:
                  id: menu_A_B_B
                  name: null
                  label: Choferes
                  route: null
                  roles: {  }
                  type: item
                  attributes: { icon: null }
                  childrens: {  }
                menu_A_B_C:
                  id: menu_A_B_C
                  name: null
                  label: Vehículos
                  route: null
                  roles: {  }
                  type: item
                  attributes: { icon: null }
                  childrens: {  }
            menu_A_C:
              id: menu_A_C
              name: null
              label: Configuración
              route: null
              roles: {  }
              type: folder
              attributes:
                icon: null
              childrens:
                menu_A_C_A:
                  id: menu_A_C_A
                  name: null
                  label: 'Cambio hora del sistema'
                  route: null
                  roles: {  }
                  type: item
                  attributes: { icon: null }
                  childrens: {  }
                menu_A_C_B:
                  id: menu_A_C_B
                  name: null
                  label: 'Cambio fecha del sistema'
                  route: null
                  roles: {  }
                  type: item
                  attributes: { icon: null }
                  childrens: {  }
        menu_B:
          id: menu_B
          name: menu_bodega
          label: Bodega
          route: bodega_principal
          roles: {  }
          type: folder
          attributes: {  }
          childrens: {  }
        menu_C:
          id: menu_C
          name: menu_taller
          label: Taller
          route: taller_principal
          roles: {  }
          type: folder
          attributes: {  }
          childrens: {  }
        menu_D:
          id: menu_D
          name: menu_combustible
          label: Combustible
          route: configuracion_combustible
          roles: {  }
          type: folder
          attributes: {  }
          childrens: {  }
        menu_E:
          id: menu_E
          name: menu_nomenclador
          label: 'Módulo Nomenclador'
          route: admin
          roles: {  }
          type: item
          attributes: {  }
          childrens: {  }
        menu_F:
          id: menu_F
          name: menu_seguridad
          label: 'Módulo Seguridad'
          route: security_usuario
          roles: {  }
          type: folder
          attributes: {  }
          childrens: {  }
