BusetaNomencladorBundle_admin_buseta_nomenclador_bundle_aceitetransmision:
    resource: "@BusetaNomencladorBundle/Controller/Aceitetransmision/"
    type:     admingenerator
    prefix:   /admin/nomenclador/aceitetransmision

BusetaNomencladoBundle_admin_buseta_nomenclado_bundle_aceitemotor:
    resource: "@BusetaNomencladorBundle/Controller/Aceitemotor/"
    type:     admingenerator
    prefix:   /admin/nomenclador/aceitemotor

buseta_bodega:
    resource: "@BusetaBodegaBundle/Resources/config/routing.yml"
    prefix:   /

buseta_taller:
    resource: "@BusetaTallerBundle/Resources/config/routing.yml"
    prefix:   /

buseta_buses:
    resource: "@BusetaBusesBundle/Resources/config/routing.yml"
    prefix:   /

BusetaNomencladorBundle_admin_buseta_nomenclador_bundle_marcamotor:
    resource: "@BusetaNomencladorBundle/Controller/Marcamotor/"
    type:     admingenerator
    prefix:   /admin/nomenclador/marcamotor

BusetaNomencladorBundle_admin_buseta_nomenclador_bundle_estilo:
    resource: "@BusetaNomencladorBundle/Controller/Estilo/"
    type:     admingenerator
    prefix:   /admin/nomenclador/estilo

BusetaNomencladorBundle_admin_buseta_nomenclador_bundle_combustible:
    resource: "@BusetaNomencladorBundle/Controller/Combustible/"
    type:     admingenerator
    prefix:   /admin/nomenclador/combustible

BusetaNomencladorBundle_admin_buseta_nomenclador_bundle_aceitehidraulico:
    resource: "@BusetaNomencladorBundle/Controller/Aceitehidraulico/"
    type:     admingenerator
    prefix:   /admin/nomenclador/aceitehidraulico

BusetaNomencladorBundle_admin_buseta_nomenclador_bundle_modelo:
    resource: "@BusetaNomencladorBundle/Controller/Modelo/"
    type:     admingenerator
    prefix:   /admin/nomenclador/modelo

BusetaNomencladorBundle_admin_buseta_nomenclador_bundle_marca:
    resource: "@BusetaNomencladorBundle/Controller/Marca/"
    type:     admingenerator
    prefix:   /admin/nomenclador/marca

BusetaNomencladorBundle_admin_buseta_nomenclador_bundle_aceitecajacambios:
    resource: "@BusetaNomencladorBundle/Controller/Aceitecajacambios/"
    type:     admingenerator
    prefix:   /admin/nomenclador/aceitecajacambios

buseta_security:
    resource: "@BusetaSecurityBundle/Resources/config/routing.yml"
    prefix:   /

BusetaNomencladorBundle_admin_buseta_nomenclador_bundle_color:
    resource: "@BusetaNomencladorBundle/Controller/Color/"
    type:     admingenerator
    prefix:   /admin/nomenclador/color

_welcome_dashboard:
    resource: "@BusetaNomencladorBundle/Resources/config/routing.yml"
    prefix:   /admin/nomenclador

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

data:
    resource: "@DataBundle/Resources/config/routing.yml"
    prefix:   /data



fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_imagine:
    resource: .
    type:     imagine