security:
    role_hierarchy:
        ROLE_THIRD_PERSON: [ROLE_USER]
        ROLE_SYSTEM_USER: [ROLE_USER]
        ROLE_ADMIN: [ROLE_THIRD_PERSON, ROLE_SYSTEM_USER, ROLE_SOLICITUD]
        ROLE_SUPER_ADMIN: [ROLE_THIRD_PERSON, ROLE_SYSTEM_USER, ROLE_ADMIN]
        ROLE_SOLICITUD: [ROLE_USER]
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
