#bitacoraserial:
#    pattern:  /
#    defaults: { _controller: "BusetaBodegaBundle:BitacoraSerial:index" }
#
#bitacoraserial_show:
#    pattern:  /{id}/show
#    defaults: { _controller: "BusetaBodegaBundle:BitacoraSerial:show" }

bitacoraserial_list:
    pattern: /list/{id}
    defaults: { _controller: "BusetaBodegaBundle:BitacoraSerial:list" }
    requirements: { _method: get }
    options:
      expose: true