bitacoraalmacen:
    pattern:  /
    defaults: { _controller: "BusetaBodegaBundle:BitacoraAlmacen:index" }

bitacoraalmacen_show:
    pattern:  /{id}/show
    defaults: { _controller: "BusetaBodegaBundle:BitacoraAlmacen:show" }

bitacoraalmacen_list:
    pattern: /list/{id}
    defaults: { _controller: "BusetaBodegaBundle:BitacoraAlmacen:list" }
    requirements: { _method: get }
    options:
      expose: true