bodega:
    pattern:  /
    defaults: { _controller: "BusetaBodegaBundle:Bodega:index" }

bodega_show:
    pattern:  /{id}/show
    defaults: { _controller: "BusetaBodegaBundle:Bodega:show" }

bodega_new:
    pattern:  /new
    defaults: { _controller: "BusetaBodegaBundle:Bodega:new" }

bodega_create:
    pattern:  /create
    defaults: { _controller: "BusetaBodegaBundle:Bodega:create" }
    requirements: { _method: post }

bodega_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BusetaBodegaBundle:Bodega:edit" }

bodega_update:
    pattern:  /{id}/update
    defaults: { _controller: "BusetaBodegaBundle:Bodega:update" }
    requirements: { _method: post|put }

bodega_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BusetaBodegaBundle:Bodega:delete" }
    requirements: { _method: post|delete }

informe_stock_create:
    pattern:  /informe_stock_create
    defaults: { _controller: "BusetaBodegaBundle:Default:create" }
    requirements: { _method: post }

informe_stock_show:
    pattern:  /informe_stock/{id}/show
    defaults: { _controller: "BusetaBodegaBundle:Default:show" }

almacen_ajax_busqueda_avanzada:
  pattern: /busqueda-avanzada/{page}/{cantResult}
  defaults: { _controller: "BusetaBodegaBundle:Bodega:busquedaAvanzada", page: 0, cantResult: 10 }
  requirements: { _method: "GET" }

bodega_ajax_productos_all:
  pattern: /select_bodega_productos_all
  defaults: { _controller: "BusetaBodegaBundle:Bodega:select_bodega_productos_all" }
  requirements: { _method: "GET" }
  options:
      expose: true

bodega_productotope_list:
    pattern: /productotope/list/{id}
    defaults: { _controller: "BusetaBodegaBundle:Bodega:listProductosTope" }
    requirements: { _method: get }
    options:
      expose: true