bodega:
    path:  /
    defaults: { _controller: "BusetaBodegaBundle:Bodega:index" }

bodega_show:
    path:  /{id}/show
    defaults: { _controller: "BusetaBodegaBundle:Bodega:show" }

bodega_new:
    path:  /new
    defaults: { _controller: "BusetaBodegaBundle:Bodega:new" }

bodega_create:
    path:  /create
    defaults: { _controller: "BusetaBodegaBundle:Bodega:create" }
    requirements: { methods: post }

bodega_edit:
    path:  /{id}/edit
    defaults: { _controller: "BusetaBodegaBundle:Bodega:edit" }

bodega_update:
    path:  /{id}/update
    defaults: { _controller: "BusetaBodegaBundle:Bodega:update" }
    requirements: { methods: post|put }

bodega_delete:
    path:  /{id}/delete
    defaults: { _controller: "BusetaBodegaBundle:Bodega:delete" }
    requirements: { methods: post|delete }

informe_stock_create:
    path:  /informe_stock_create
    defaults: { _controller: "BusetaBodegaBundle:Default:create" }
    requirements: { methods: post }

informe_stock_show:
    path:  /informe_stock/{id}/show
    defaults: { _controller: "BusetaBodegaBundle:Default:show" }

almacen_ajax_busqueda_avanzada:
  path: /busqueda-avanzada/{page}/{cantResult}
  defaults: { _controller: "BusetaBodegaBundle:Bodega:busquedaAvanzada", page: 0, cantResult: 10 }
  requirements: { methods: "GET" }

bodega_ajax_productos_all:
  path: /select_bodega_productos_all
  defaults: { _controller: "BusetaBodegaBundle:Bodega:select_bodega_productos_all" }
  requirements: { methods: "GET" }
  options:
      expose: true

bodega_productomaxmin:
    path:  /productomaxmin/{id}
    defaults: { _controller: "BusetaBodegaBundle:Bodega:productoTope" }
    requirements: { methods: post|get }

bodega_productotope_list:
    path: /productotope/list/{id}
    defaults: { _controller: "BusetaBodegaBundle:Bodega:listProductosTope" }
    requirements: { methods: get }
    options:
      expose: true
