costo_producto:
    pattern:  /
    defaults: { _controller: "BusetaBodegaBundle:CostoProducto:index" }

costo_producto_show:
    pattern:  /{id}/show
    defaults: { _controller: "BusetaBodegaBundle:CostoProducto:show" }

costo_producto_new:
    pattern:  /new
    defaults: { _controller: "BusetaBodegaBundle:CostoProducto:new" }

costo_producto_create:
    pattern:  /create
    defaults: { _controller: "BusetaBodegaBundle:CostoProducto:create" }
    requirements: { _method: post }

costo_producto_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BusetaBodegaBundle:CostoProducto:edit" }

costo_producto_update:
    pattern:  /{id}/update
    defaults: { _controller: "BusetaBodegaBundle:CostoProducto:update" }
    requirements: { _method: post|put }

costo_producto_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BusetaBodegaBundle:CostoProducto:delete" }
    requirements: { _method: post|delete }

comprobarCosto:
  pattern: /comprobarCosto
  defaults: { _controller: "BusetaBodegaBundle:CostoProducto:comprobarCosto" }
  requirements: { _method: "GET" }
  options:
      expose: true

costo_ajax_productos_all:
  pattern: /select_costo_productos_all
  defaults: { _controller: "BusetaBodegaBundle:CostoProducto:select_costo_productos_all" }
  requirements: { _method: "GET" }
  options:
      expose: true
