inventario_fisoc_linea:
    path:  /
    defaults: { _controller: "BusetaBodegaBundle:InventarioFisicoLinea:index" }

inventario_fisico_linea_show:
    path:  /{id}/show
    defaults: { _controller: "BusetaBodegaBundle:InventarioFisicoLinea:show" }

inventario_fisico_linea_new:
    path:  /new
    defaults: { _controller: "BusetaBodegaBundle:InventarioFisicoLinea:new" }

inventario_fisico_linea_create:
    path:  /create
    defaults: { _controller: "BusetaBodegaBundle:InventarioFisicoLinea:create" }
    requirements: { methods: post }

inventario_fisico_linea_compra_create:
    path:  /create
    defaults: { _controller: "BusetaBodegaBundle:InventarioFisicoLinea:create_compra" }
    requirements: { methods: post }

inventario_fisico_linea_edit:
    path:  /{id}/edit
    defaults: { _controller: "BusetaBodegaBundle:InventarioFisicoLinea:edit" }

inventario_fisico_linea_update:
    path:  /{id}/update
    defaults: { _controller: "BusetaBodegaBundle:InventarioFisicoLinea:update" }
    requirements: { methods: post|put }

inventario_fisico_linea_delete:
    path:  /{id}/delete
    defaults: { _controller: "BusetaBodegaBundle:InventarioFisicoLinea:delete" }
    requirements: { methods: post|delete }
