inventariofisico:
    path:  /
    defaults: { _controller: "BusetaBodegaBundle:InventarioFisico:index" }

inventariofisico_show:
    path:  /{id}/show
    defaults: { _controller: "BusetaBodegaBundle:InventarioFisico:show" }

inventariofisico_new:
    path:  /new
    defaults: { _controller: "BusetaBodegaBundle:InventarioFisico:new" }

inventariofisico_create:
    path:  /create
    defaults: { _controller: "BusetaBodegaBundle:InventarioFisico:create" }
    requirements: { methods: post }

inventariofisico_edit:
    path:  /{id}/edit
    defaults: { _controller: "BusetaBodegaBundle:InventarioFisico:edit" }

inventariofisico_update:
    path:  /{id}/update
    defaults: { _controller: "BusetaBodegaBundle:InventarioFisico:update" }
    requirements: { methods: post|put }

inventariofisico_delete:
    path:  /{id}/delete
    defaults: { _controller: "BusetaBodegaBundle:InventarioFisico:delete" }
    requirements: { methods: post|delete }

procesarInventarioFisico:
    path:  /{id}/procesarInventarioFisico
    defaults: { _controller: "BusetaBodegaBundle:InventarioFisico:procesarInventarioFisico" }

completarInventarioFisico:
    path:  /{id}/completarInventarioFisico
    defaults: { _controller: "BusetaBodegaBundle:InventarioFisico:completarInventarioFisico" }

inventarioFisico_ajax_busqueda_avanzada:
  path: /busqueda-avanzada/{page}/{cantResult}
  defaults: { _controller: "BusetaBodegaBundle:InventarioFisico:busquedaAvanzada", page: 0, cantResult: 10 }
  requirements: { methods: "GET" }
