movimiento:
    path:  /
    defaults: { _controller: "BusetaBodegaBundle:Movimiento:index" }

movimiento_show:
    path:  /{id}/show
    defaults: { _controller: "BusetaBodegaBundle:Movimiento:show" }

movimiento_new:
    path:  /new
    defaults: { _controller: "BusetaBodegaBundle:Movimiento:new" }

movimiento_create:
    path:  /create
    defaults: { _controller: "BusetaBodegaBundle:Movimiento:create" }
    requirements: { methods: post }

movimiento_edit:
    path:  /{id}/edit
    defaults: { _controller: "BusetaBodegaBundle:Movimiento:edit" }

movimiento_update:
    path:  /{id}/update
    defaults: { _controller: "BusetaBodegaBundle:Movimiento:update" }
    requirements: { methods: post|put }

movimiento_delete:
    path:  /{id}/delete
    defaults: { _controller: "BusetaBodegaBundle:Movimiento:delete" }
    requirements: { methods: get|post|delete }

movimientos_productos_create:
    path:  /movimientos/create
    defaults: { _controller: "BusetaBodegaBundle:Movimiento:create_movimiento" }
    requirements: { methods: post }

movimientos_ajax_almacenOrigen_almacenDestino:
  path: /select_almacenOrigen_almacenDestino
  defaults: { _controller: "BusetaBodegaBundle:Movimiento:select_almacenOrigen_almacenDestino" }
  requirements: { methods: "GET" }
  options:
      expose: true

procesarMovimiento:
  path:  /{id}/procesar
  defaults: { _controller: "BusetaBodegaBundle:Movimiento:procesarMovimiento" }

completarMovimiento:
  path:  /{id}/completar
  defaults: { _controller: "BusetaBodegaBundle:Movimiento:completarMovimiento" }
