necesidad_material_linea:
    pattern:  /
    defaults: { _controller: "BusetaBodegaBundle:NecesidadMaterialLinea:index" }

necesidad_material_linea_show:
    pattern:  /{id}/show
    defaults: { _controller: "BusetaBodegaBundle:NecesidadMaterialLinea:show" }

necesidad_material_linea_new:
    pattern:  /new
    defaults: { _controller: "BusetaBodegaBundle:NecesidadMaterialLinea:new" }

necesidad_material_linea_create:
    pattern:  /create
    defaults: { _controller: "BusetaBodegaBundle:NecesidadMaterialLinea:create" }
    requirements: { _method: post }

necesidad_material_linea_compra_create:
    pattern:  /create
    defaults: { _controller: "BusetaBodegaBundle:NecesidadMaterialLinea:create_compra" }
    requirements: { _method: post }

necesidad_material_linea_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BusetaBodegaBundle:NecesidadMaterialLinea:edit" }

necesidad_material_linea_update:
    pattern:  /{id}/update
    defaults: { _controller: "BusetaBodegaBundle:NecesidadMaterialLinea:update" }
    requirements: { _method: post|put }

necesidad_material_linea_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BusetaBodegaBundle:NecesidadMaterialLinea:delete" }
    requirements: { _method: post|delete }
