pedido_compra_linea:
    pattern:  /
    defaults: { _controller: "BusetaBodegaBundle:PedidoCompraLinea:index" }

pedido_compra_linea_show:
    pattern:  /{id}/show
    defaults: { _controller: "BusetaBodegaBundle:PedidoCompraLinea:show" }

pedido_compra_linea_new:
    pattern:  /new
    defaults: { _controller: "BusetaBodegaBundle:PedidoCompraLinea:new" }

pedido_compra_linea_create:
    pattern:  /create
    defaults: { _controller: "BusetaBodegaBundle:PedidoCompraLinea:create" }
    requirements: { _method: post }

pedido_compra_linea_compra_create:
    pattern:  /create
    defaults: { _controller: "BusetaBodegaBundle:PedidoCompraLinea:create_compra" }
    requirements: { _method: post }

pedido_compra_linea_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BusetaBodegaBundle:PedidoCompraLinea:edit" }

pedido_compra_linea_update:
    pattern:  /{id}/update
    defaults: { _controller: "BusetaBodegaBundle:PedidoCompraLinea:update" }
    requirements: { _method: post|put }

pedido_compra_linea_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BusetaBodegaBundle:PedidoCompraLinea:delete" }
    requirements: { _method: post|delete }
