precio_producto:
    path:  /
    defaults: { _controller: "BusetaBodegaBundle:PrecioProducto:index" }

precio_producto_show:
    path:  /{id}/show
    defaults: { _controller: "BusetaBodegaBundle:PrecioProducto:show" }

precio_producto_new:
    path:  /new
    defaults: { _controller: "BusetaBodegaBundle:PrecioProducto:new" }

precio_producto_create:
    path:  /create
    defaults: { _controller: "BusetaBodegaBundle:PrecioProducto:create" }
    requirements: { methods: post }

precio_producto_edit:
    path:  /{id}/edit
    defaults: { _controller: "BusetaBodegaBundle:PrecioProducto:edit" }

precio_producto_update:
    path:  /{id}/update
    defaults: { _controller: "BusetaBodegaBundle:PrecioProducto:update" }
    requirements: { methods: post|put }

precio_producto_delete:
    path:  /{id}/delete
    defaults: { _controller: "BusetaBodegaBundle:PrecioProducto:delete" }
    requirements: { methods: post|delete }

comprobarPrecio:
  path: /comprobarPrecio
  defaults: { _controller: "BusetaBodegaBundle:PrecioProducto:comprobarPrecio" }
  requirements: { methods: "GET" }
  options:
      expose: true

precio_ajax_productos_all:
  path: /select_precio_productos_all
  defaults: { _controller: "BusetaBodegaBundle:PrecioProducto:select_precio_productos_all" }
  requirements: { methods: "GET" }
  options:
      expose: true
