productotope:
    path:  /
    defaults: { _controller: "BusetaBodegaBundle:ProductoTope:index" }

productotope_show:
    path:  /{id}/show
    defaults: { _controller: "BusetaBodegaBundle:ProductoTope:show" }

productotope_new:
    path:  /new
    defaults: { _controller: "BusetaBodegaBundle:ProductoTope:new" }

productotope_create:
    path:  /create
    defaults: { _controller: "BusetaBodegaBundle:ProductoTope:create" }
    requirements: { methods: post }

productotope_edit:
    path:  /{id}/edit
    defaults: { _controller: "BusetaBodegaBundle:ProductoTope:edit" }

productotope_update:
    path:  /{id}/update
    defaults: { _controller: "BusetaBodegaBundle:ProductoTope:update" }
    requirements: { methods: post|put }

productotope_delete:
    path:  /{id}/delete
    defaults: { _controller: "BusetaBodegaBundle:ProductoTope:delete" }
    requirements: { methods: get|post|delete }
