producto:
    path:  /
    defaults: { _controller: "BusetaBodegaBundle:Producto:index" }

producto_show:
    path:  /{id}/show
    defaults: { _controller: "BusetaBodegaBundle:Producto:show" }

producto_new:
    path:  /new
    defaults: { _controller: "BusetaBodegaBundle:Producto:new" }

producto_create:
    path:  /create
    defaults: { _controller: "BusetaBodegaBundle:Producto:create" }
    requirements: { methods: post }

producto_edit:
    path:  /{id}/edit
    defaults: { _controller: "BusetaBodegaBundle:Producto:edit" }

producto_update:
    path:  /{id}/update
    defaults: { _controller: "BusetaBodegaBundle:Producto:update" }
    requirements: { methods: post|put }

producto_delete:
    path:  /{id}/delete
    defaults: { _controller: "BusetaBodegaBundle:Producto:delete" }
    requirements: { methods: post|delete }

producto_ajax_grupos_subgrupos:
  path: /select_grupo_subgrupo
  defaults: { _controller: "BusetaBodegaBundle:Producto:select_grupo_subgrupo" }
  requirements: { methods: "GET" }
  options:
      expose: true

producto_ajax_productos_all:
  path: /select_productos_all
  defaults: { _controller: "BusetaBodegaBundle:Producto:select_productos_all" }
  requirements: { methods: "GET" }
  options:
      expose: true

producto_filter:
  path: /producto_filter
  defaults: { _controller: "BusetaBodegaBundle:Producto:productoFilter" }
  requirements: { methods: "GET" }
  options:
      expose: true

producto_ajax_busqueda_avanzada:
  path: /busqueda-avanzada/{page}/{cantResult}
  defaults: { _controller: "BusetaBodegaBundle:Producto:busquedaAvanzada", page: 0, cantResult: 10 }
  requirements: { methods: "GET" }

producto_bitacora:
    path:  /{id}/productoBitacora
    defaults: { _controller: "BusetaBodegaBundle:Producto:productoBitacora" }
