<?php

namespace Buseta\BodegaBundle\Entity\Repository;

use Buseta\BodegaBundle\Entity\Bodega;
use Buseta\BodegaBundle\Entity\Producto;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * InputStackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InputStackRepository extends EntityRepository
{
    public function inputsProductoBodega(Producto $producto, Bodega $bodega)
    {
        $qb = $this->createQueryBuilder('p');
        $query = $qb->where($qb->expr()->eq(true,true));

        $query->innerJoin('p.bitacora', 'bitacora')
            ->where($qb->expr()->andX((
            $qb->expr()->eq('bitacora.producto',':producto')
            ), $qb->expr()->eq('bitacora.almacen',':almacen')
            ))
            ->setParameter('producto', $producto)
            ->setParameter('almacen', $bodega);

        $query->andWhere($query->expr()->gt('p.remainingQuantity', 0));

        $query->orderBy('p.date', 'ASC');
        try {
            return $query->getQuery()->getResult();
        } catch (NoResultException $e) {
            return array();
        }
    }

}