sequence:
    path:  /
    defaults: { _controller: "HatueySoftSequenceBundle:Sequence:index" }

sequence_show:
    path:  /{id}/show
    defaults: { _controller: "HatueySoftSequenceBundle:Sequence:show" }

sequence_new:
    path:  /new
    defaults: { _controller: "HatueySoftSequenceBundle:Sequence:new" }

sequence_create:
    path:  /create
    defaults: { _controller: "HatueySoftSequenceBundle:Sequence:create" }
    requirements: { methods: post }

sequence_edit:
    path:  /{id}/edit
    defaults: { _controller: "HatueySoftSequenceBundle:Sequence:edit" }

sequence_update:
    path:  /{id}/update
    defaults: { _controller: "HatueySoftSequenceBundle:Sequence:update" }
    requirements: { methods: post|put }

#sequence_delete:
#    path:  /{id}/delete
#    defaults: { _controller: "HatueySoftSequenceBundle:Sequence:delete" }
#    requirements: { methods: post|delete }
