hatuey_soft_sequence:
    resource: "@HatueySoftSequenceBundle/Resources/config/routing/sequence.yml"
    prefix:   /sequence

#hatuey_soft_sequence_annotation:
#  resource: "@HatueySoftSequenceBundle/Controller/SecuenciaController.php"
#  type:     annotation
