parameters:
#    hatuey_soft_sequence.example.class: HatueySoft\SequenceBundle\Example

services:
  hatuey_soft.sequence.manager:
    class: HatueySoft\SequenceBundle\Managers\SequenceManager
    arguments: [@doctrine.orm.entity_manager, %hatuey_soft_sequence.config%, @logger]
#    hatuey_soft_sequence.example:
#        class: %hatuey_soft_sequence.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
