parameters:
#    hatuey_soft_sequence.example.class: HatueySoft\SequenceBundle\Example

services:
#    hatuey_soft_sequence.example:
#        class: %hatuey_soft_sequence.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]