generator: admingenerator.generator.doctrine
params:
    model: Buseta\BodegaBundle\Entity\Bodega
    namespace_prefix: Buseta
    concurrency_lock: ~
    bundle_name: BodegaBundle
    pk_requirement: ~
    fields:
      codigo:
        label: Código
      nombre:
        label: Nombre
      descripcion:
        label: Descripción
      entidad:
         label: Entidad
      entidad:
         label: Dirección
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Listado de bodegas
            display: [nombre, codigo, descripcion, entidad, direccion]
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [nombre, codigo, descripcion, entidad, direccion]
    new:
        params:
            title: Nueva bodega
            display: [nombre, codigo, descripcion, entidad, direccion]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Usted está modificando el producto \"%object%\"|{ %object%: Bodega.nombre }|"
            display: [nombre, codigo, descripcion, entidad, direccion]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Usted está mostrando los datos del producto \"%object%\"|{ %object%: Bodega.nombre }|"
            display: [nombre, codigo, descripcion, entidad, direccion]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
