generator: admingenerator.generator.doctrine
params:
    model: Buseta\BodegaBundle\Entity\Producto
    namespace_prefix: Buseta
    concurrency_lock: ~
    bundle_name: BodegaBundle
    pk_requirement: ~
    fields:
      codigo:
        label: C칩digo
      descripcion:
        label: Descripci칩n
      nombre:
        label: Nombre
      unidad_medida:
         label: U/M
      costo:
         label: Costo
      precio_salida:
         label: Precio de Salida
      peso:
         label: Peso
      volumen:
         label: Volumen
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Listado de productos
            display: [nombre, codigo, descripcion, unidad_medida, costo, precio_salida, peso, volumen]
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [nombre, codigo, descripcion, unidad_medida, costo, precio_salida, peso, volumen]
    new:
        params:
            title: Nuevo producto
            display: [nombre, codigo, descripcion, unidad_medida, costo, precio_salida, peso, volumen]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Usted est치 modificando el producto \"%object%\"|{ %object%: Producto.nombre }|"
            display: [nombre, codigo, descripcion, unidad_medida, costo, precio_salida, peso, volumen]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Usted est치 mostrando los datos del producto \"%object%\"|{ %object%: Producto.nombre }|"
            display: [nombre, codigo, descripcion, unidad_medida, costo, precio_salida, peso, volumen]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
