buseta_bodega_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: BusetaBodegaBundle:Default:index }

bodega_principal:
    pattern:  /modulo/bodega
    defaults: { _controller: "BusetaBodegaBundle:Bodega:principal" }

bodega_informe_stock:
    pattern:  /modulo/bodega/informe_stock
    defaults: { _controller: "BusetaBodegaBundle:InformeStock:index" }

bodega_informe_costos:
    pattern:  /modulo/bodega/informe_costos
    defaults: { _controller: "BusetaBodegaBundle:Informe:informeCostos" }
