parameters:
#    buseta_bodega.example.class: Buseta\BodegaBundle\Example

services:
    bodega.movimiento.type:
        class: Buseta\BodegaBundle\Form\Type\MovimientoType
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: form.type, alias: 'buseta_bodegabundle_movimiento'}
