parameters:
    consecutivoCompra: 89

services:
    bodega.movimiento.type:
        class: Buseta\BodegaBundle\Form\Type\MovimientoType
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: form.type, alias: 'buseta_bodegabundle_movimiento'}
    bodega.compra.type:
        class: Buseta\BodegaBundle\Form\Type\PedidoCompraType
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: form.type, alias: 'bodega_pedido_compra'}
