generator: admingenerator.generator.doctrine
params:
    model: Buseta\NomencladorBundle\Entity\Modelo
    namespace_prefix: Buseta
    concurrency_lock: ~
    bundle_name: NomencladorBundle
    pk_requirement: ~
    fields:
      codigo:
            label: C칩digo
      valor:
            label: Valor
      marca:
            label: Marca
      descripcion:
            label: Descripci칩n
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Listado de modelos
            display: [codigo, valor, marca, descripcion]
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [codigo, valor, marca, descripcion]
    new:
        params:
            title: Adicionar nuevo modelo
            display: [codigo, valor, marca, descripcion]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Usted est치 modificando el modelo: \"%object%\"|{ %object%: Modelo.valor }|"
            display: [codigo, valor, marca, descripcion]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Usted est치 mostrando el modelo: \"%object%\"|{ %object%: Modelo.valor }|"
            display: [codigo, valor, marca, descripcion]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
