generator: admingenerator.generator.doctrine
params:
    model: Buseta\NomencladorBundle\Entity\Subgrupo
    namespace_prefix: Buseta
    concurrency_lock: ~
    bundle_name: NomencladorBundle
    pk_requirement: ~
    fields:
      valor:
            label: Valor
      grupo:
            label: Grupo
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Listado de subgrupos
            display: [valor, grupo]
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
             display: [valor, grupo]
    new:
        params:
            title: Adicionar nuevo subgrupo
            display: [valor, grupo]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Usted está modificando el subgrupo: \"%object%\"|{ %object%: Subgrupo.valor }|"
            display: [valor, grupo]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Usted está mostrando los datos del subgrupo: \"%object%\"|{ %object%: Subgrupo.valor }|"
            display: [valor, grupo]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
