generator: admingenerator.generator.doctrine
params:
    model: Buseta\NomencladorBundle\Entity\UOM
    namespace_prefix: Buseta
    concurrency_lock: ~
    bundle_name: NomencladorBundle
    pk_requirement: ~
    fields:
      valor:
            label: Valor
      codigo:
            label: Código
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Listado de unidades de medidas (UOM)
            display: [valor, codigo]
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [valor, codigo]
    new:
        params:
            title: Adicionar nueva unidad de medida
            display: [valor, codigo]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Usted está modificando la unidad de medida: \"%object%\"|{ %object%: UOM.valor }|"
            display: [valor, codigo]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Usted está mostrando los datos de la unidad de medida: \"%object%\"|{ %object%: UOM.valor }|"
            display: [valor, codigo]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
