parameters:
#    data.example.class: Buseta\DataBundle\Example

services:
    buses.combustible_configuracion_combustible.type:
        class: Buseta\CombustibleBundle\Form\Type\ConfiguracionCombustibleType
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: form.type, alias: 'combustible_configuracion_combustible'}

    buses.combustible_servicio_combustible.type:
        class: Buseta\CombustibleBundle\Form\Type\ServicioCombustibleType
        arguments: [@doctrine.orm.entity_manager, @service_container, @core.fecha_sistema, @core.cambiohora_sistema]
        tags:
            - {name: form.type, alias: 'combustible_servicio_combustible'}

    buses.combustible_lista_negra_combustible.type:
        class: Buseta\CombustibleBundle\Form\Type\ListaNegraCombustibleType
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: form.type, alias: 'combustible_lista_negra_combustible'}

    core.twig.fecha_sistema_extension:
        class: Buseta\CoreBundle\Twig\FechaSistemaExtension
        arguments:
            - @core.fecha_sistema
        tags:
            - { name: twig.extension }

    #VALIDATORS
    buseta.combustible.marchamo1valido.validador:
        class: Buseta\CombustibleBundle\Validator\Constraints\Marchamo1ValidoValidator
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - {name: validator.constraint_validator, alias: combustible_marchamo1valido_validador }
    buseta.combustible.marchamo2valido.validador:
        class: Buseta\CombustibleBundle\Validator\Constraints\Marchamo2ValidoValidator
        arguments:
            - @doctrine.orm.entity_manager
            - @logger
        tags:
            - {name: validator.constraint_validator, alias: combustible_marchamo2valido_validador }

    buseta.combustible.capacidad_tanque.validador:
        class: Buseta\CombustibleBundle\Validator\Constraints\CapacidadTanqueValidoValidator
        tags:
            - {name: validator.constraint_validator, alias: capacidadTanque_validador }


    buseta.combustible.odometro.validador:
        class: Buseta\CombustibleBundle\Validator\Constraints\OdometroValidator
        arguments:
            - @doctrine.orm.entity_manager
            - @logger
        tags:
            - {name: validator.constraint_validator, alias: combustible_odometro_validator }

    #SUBSCRIBERS
    buses.combustible.servicio_combustible.subscriber:
        class: Buseta\CombustibleBundle\EventListener\ServicioCombustibleSubscriber
        arguments:
            - @logger
        tags:
            - { name: kernel.event_subscriber }

    #MANAGER
    buseta.combustible.servicio_combustible.manager:
        class: Buseta\CombustibleBundle\Manager\ServicioCombustibleManager
        arguments:
            - @doctrine.orm.entity_manager
            - @logger
            - @event_dispatcher

    buseta.twig.server_expose_extension:
            class: Buseta\CombustibleBundle\Twig\ServerExposeExtension
            arguments: [@service_container]
            tags:
                - { name: twig.extension }
