parameters:
#    data.example.class: Buseta\DataBundle\Example

services:
    buses.combustible_configuracion_combustible.type:
        class: Buseta\CombustibleBundle\Form\Type\ConfiguracionCombustibleType
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: form.type, alias: 'combustible_configuracion_combustible'}
    buses.combustible_servicio_combustible.type:
        class: Buseta\CombustibleBundle\Form\Type\ServicioCombustibleType
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: form.type, alias: 'combustible_servicio_combustible'}
    buses.combustible_lista_negra_combustible.type:
        class: Buseta\CombustibleBundle\Form\Type\ListaNegraCombustibleType
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: form.type, alias: 'combustible_lista_negra_combustible'}
