parameters:
#    data.example.class: Buseta\DataBundle\Example

services:
    buses.combustible_configuracion_combustible.type:
        class: Buseta\CombustibleBundle\Form\Type\ConfiguracionCombustibleType
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: form.type, alias: 'combustible_configuracion_combustible'}

    buses.combustible_servicio_combustible.type:
        class: Buseta\CombustibleBundle\Form\Type\ServicioCombustibleType
        arguments: [@doctrine.orm.entity_manager, @service_container, @core.fecha_sistema, @core.cambiohora_sistema]
        tags:
            - {name: form.type, alias: 'combustible_servicio_combustible'}

    buses.combustible_lista_negra_combustible.type:
        class: Buseta\CombustibleBundle\Form\Type\ListaNegraCombustibleType
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: form.type, alias: 'combustible_lista_negra_combustible'}

    core.twig.fecha_sistema_extension:
        class: Buseta\CoreBundle\Twig\FechaSistemaExtension
        arguments:
            - @core.fecha_sistema
        tags:
            - { name: twig.extension }

    #VALIDATOR
    buses.marchamo1.validador:
        class: Buseta\CombustibleBundle\Validator\Constraints\Marchamo1ValidoValidator
        arguments:
            - @security.context
            - @doctrine.orm.entity_manager
        tags:
            - {name: validator.constraint_validator, alias: marchamo1_validador}
