role_grants:
    path:     /
    defaults: { _controller: "HatueySoftSecurityBundle:Route:route" }

role_route_edit:
    path:     /{name}/edit
    defaults: { _controller: "HatueySoftSecurityBundle:Role:edit" }

#role_route_delete:
#    path:     /{name}/delete
#    defaults: { _controller: "HatueySoftSecurityBundle:Role:delete" }

role_add_path:
    path: /role/add/path
    defaults: { _controller: "HatueySoftSecurityBundle:Role:add" }

role_delete_path:
    path: /role/delete/path
    defaults: { _controller: "HatueySoftSecurityBundle:Role:remove" }

role_new_el:
    path: /role/new/path
    defaults: { _controller: "HatueySoftSecurityBundle:Role:addrole" }

role_del_el:
    path: /role/del/path
    defaults: { _controller: "HatueySoftSecurityBundle:Role:delrole" }

role_route_add:
    path: /role/route/add
    defaults: { _controller: "HatueySoftSecurityBundle:Route:roleToRoute"  }

role_route_delete:
    path: /role/route/delete
    defaults: { _controller: "HatueySoftSecurityBundle:Route:unBindRole"  }