BusetaBuses_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: BusetaBusesBundle:Default:index }
BusetaBusesBundle_autobus:
        resource: "@BusetaBusesBundle/Resources/config/routing/autobus.yml"
        prefix:   /autobus
